{% set name = "ccls" %}
{% set version = "0.20190823.3" %}

package:
  name: {{name}}
  version: {{version}}

source:
  git_rev: {{version}}
  git_url: https://github.com/MaskRay/{{name}}.git
  patches:
    - indexer.cc.patch

build:
  number: '0'
  include_recipe: False

requirements:
  build:
    - gxx_linux-64
    - clang 8.0.0
    - clangdev 8.0.0
    - llvmdev 8.0.0
    - rapidjson
    - cmake
    - git
    - patch

test:
  commands:
    - which ccls
    - ccls --version

about:
  home: https://github.com/MaskRay/ccls
  license: Free software (Apache-2.0)
  summary: a C/C++/Objective-C language server
  description: |
    C/C++/ObjC language server supporting cross references, hierarchies, completion and semantic highlighting.  The recipe is maintained at https://github.com/bobbiewang/conda-recipes.

extra:
  recipe-maintainers:
    - bobbiewang
